name: Enforce Gates (RM-01)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  gate-g1-bundle-contract:
    name: Gate G1 - Bundle Contract
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Run Gate G1 enforcement
      run: |
        python standards/rm01/enforce_bundle_contract.py
    
    - name: Summary
      if: always()
      run: |
        if [ $? -eq 0 ]; then
          echo "✓ Gate G1 PASSED - Bundle contract satisfied"
        else
          echo "✗ Gate G1 FAILED - Bundle contract violations found"
          echo "See errors above for details"
          exit 1
        fi

  all-gates-summary:
    name: All Gates Summary
    runs-on: ubuntu-latest
    needs: [gate-g1-bundle-contract]
    if: always()
    
    steps:
    - name: Check gate results
      run: |
        echo "=== RG² Gate Enforcement Summary ==="
        echo ""
        echo "Gate G1 (Bundle Contract): ${{ needs.gate-g1-bundle-contract.result }}"
        echo ""
        
        if [ "${{ needs.gate-g1-bundle-contract.result }}" != "success" ]; then
          echo "❌ GATES FAILED"
          echo "At least one gate did not pass. See job details above."
          exit 1
        else
          echo "✅ ALL GATES PASSED"
          echo "Repository satisfies all enforced constraints."
        fi
